services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/workspace
    command: npm install -g typescript
    entrypoint: >
      /bin/sh -c "sleep 86400"